### PR TITLE
[Refractor 1] move data to seperate files for better code visibility

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
It was little hard to dig through the unnecessary data to visit the actual code.
Moved all the data inside `HomeView` to a seperate file for better code visibility.

### CODE REVIEW

**Comment by GangaChatrvedi** [comment]
You should rebase first and then make changes as the data has been changed.

**Comment by Abhishek-kumar09** [comment]
Now since the development branch is merged into master, should I make this PR against master or leave as it against development

**Comment by Abhishek-kumar09** [comment]
Done @GangaChatrvedi

**Comment by GangaChatrvedi** [comment]
Nice work! I've sent you invitation for this project.

**Comment by Abhishek-kumar09** [comment]
Oh thank you very much for the invitation...celebrating now....hurray!!!
@GangaChatrvedi I would like to ask a thing that for now on should new PRs be made against master branch, rather than development (cause all codes are merged into master).

**Comment by GangaChatrvedi** [comment]
All PRS should still be made against development.

**Pull request merged**
