### PR TITLE
fixed login button covering the  cfc title and home-view hero page

### LINKED ISSUE #101: Login button overlapping with logo in mobile view
WhatsApp Image 2020-09-28 at 7 29 00 AM

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes #101, #104 
Also fixes hero page of homeview:
Earlier: (on smaller screens)
[see overlapped hero image (before)](https://user-images.githubusercontent.com/48255244/94449631-ed867b80-01c9-11eb-8728-68b9f66ef133.png)

### CODE REVIEW

**Comment by KeenWarrior** [comment]
The login button is getting hidden on the small screen. That will create an issue in launching login when someone is not logged in and apply for the course.

**Comment by Abhishek-kumar09** [comment]
I thought it too, but we have events and courses pages where they would have to login and the button is visible.

But yes totally agree with the fact that we require a Login button at Top always, what should be the design as we can only consider login button of width same as avatar so that it does not overlap the title.

**Comment by Abhishek-kumar09** [comment]
image
We can also omit this long title and just keep cfc logo at the top.

**Comment by Abhishek-kumar09** [comment]
Notes: 
- Login is moved to drawer
- When user is logged in the avatar is rendered on topbar
- When user is logged off the Login button is rendered inside drawer
- Moved dialog to Topbar from Account.

**Review by KeenWarrior — APPROVED** [review]

**Pull request merged**
