### PR TITLE
Optimized static assets for faster loading time

### PR DESCRIPTION
**Pull request by parshnt**
Optimized the resolution of static images to make loading times faster.

Should solve #42 and #60

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Hey @parshnt , There are some merge confilcts, please resolve them. I f you get any problem then tell us here. We are here to help.

**Comment by parshnt** [comment]
Hey @Abhishek-kumar09, I've resolved all the merge conflicts, and the checks are also passing successfully.

**Comment by Abhishek-kumar09** [comment]
Thanks for your PR @parshnt.
 @KeenWarrior or @GangaChatrvedi will approve then we are OK to merge.

**Comment by KeenWarrior** [comment]
Hello @parshnt

Thanks for great work and nice observation.

Assets have been updated via different PR. So we will not be able to merge this PR.

But with your efforts in this project we would love to assign you as collaborator on project.

Sending you invite for same.

**Comment by parshnt** [comment]
@KeenWarrior, I noticed during the same when I resolved the conflicts. this solves #60 and makes this PR obsolete.

Sure, I'll accept the invite :)

**Pull request closed without merging**
