### PR TITLE
Fixed issue #123

### PR DESCRIPTION
**Pull request by ujjwal404**
Removed line to console log firebase auth token.
Screenshot 2020-10-05 at 5 39 34 PM

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Firebase tokens are time-bound and expires when user logs out, and every time the user logs in it generates a new token.
So, Is there any loophole that this token is opening when exposed to the user?

**Comment by ujjwal404** [comment]
No there is no such loophole but there is a really little chance if someone manages to do a successful XSS attack on client's browser then they might be able to use that loken to get the data.

**Comment by Abhishek-kumar09** [comment]
I cant test whether it is not showing the token again with this code, because the netlify domain is not registered with oauth.
Did you have confirmed at your end that this token is now not visible.

**Comment by ujjwal404** [comment]
Sorry I've not confirmed this but authServices.js is the only file that uses token from auth.js. In auth.js file accessToken has been passed to setSession function which prints it to console. No other external function uses access token from auth.js, I've checked each external file that auth.js imports and uses its functions or states.

**Comment by Abhishek-kumar09** [comment]
Ok, thats cool.
But I want to ask that if you can see the token again in your console after this change.

**Comment by ujjwal404** [comment]
No, its not there and everything is working fine.

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
