### PR TITLE
Added "Explore" section in footer

### LINKED ISSUE #58: Add link for pledge website
Adding a section in footer for important links might be a good way to go.
Pledge website: https://pledge.codeforcause.org/

### PR DESCRIPTION
**Pull request by pandafy**
Replace "Blogs" in footer by "Explore" and added links to following
platforms:
 - CFC's Medium
 - CFC's GitHub
 - CFC's  pledge website

Closes #58

P.S: I am not sure whether this is the right way to do it. I am fairly new to React, and the work is outcome of my instincts. I happy to bring changes if necessary.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
The right half of the footer looks very conjusted compared to the left part. I think we can move explore section to some pixels left.
image

An other approach could be, rendering only icons and when user hovers on it, It should show the description (like pledge with us, read with us, etc)
 We can also add [codingJuniors](https://github.com/codingjuniors) to the list.

**Comment by pandafy** [comment]
> The right half of the footer looks very conjusted compared to the left part. I think we can move explore section to some pixels left.

I agree. I will bring this change. 


> An other approach could be, rendering only icons and when user hovers on it, It should show the description (like pledge with us, read with us, etc)

I don't like this, since it brings element of surprise. If we are already stacking the icons vertically, it will look very weird to have them without any text. 

> We can also add [codingJuniors](https://github.com/codingjuniors) to the list.

I didn't know about this. I'll add this.

**Comment by KeenWarrior** [comment]
We have a thought of different footer. @Abhishek-kumar09 Can you create one issue including figma image of that?

@pandafy Implementing that footer will solve this issue. We would love if you can help us in that.

**Comment by Abhishek-kumar09** [comment]
> If we are already stacking the icons vertically, it will look very weird to have them without any text.

Oh, I thought we could stack it horizontally that way, Nevertheless, the changes are accurate and is looking great.
Thanks for your efforts.

**Comment by pandafy** [comment]
@Abhishek-kumar09 can it be flag as `hacktober-accepted` or would you like me to continue the footer work described by @KeenWarrior in this PR only?

**Comment by Abhishek-kumar09** [comment]
@pandafy Only owners can creates labels and we also have to create hacktoberfest label and add hacktoberfest topic to the repo.
Here, your changes are excellent and counts towards mergeability.

**Pull request closed without merging**
