### PR TITLE
feat: add new eslint and prettier rules

### PR DESCRIPTION
**Pull request by bklynate**
PR for issue: https://github.com/codeforcauseorg/codeforcause.org/issues/122

### CODE REVIEW

**Comment by bklynate** [comment]
@maverick-27

**Comment by Abhishek-kumar09** [comment]
@bklynate Will you make another commit within this PR and run `npm run format` on that to see what are the changes that have introduced with this PR.

**Comment by Abhishek-kumar09** [comment]
I guess it was already prompting to add semicolon.

**Comment by bklynate** [comment]
I ran `npm run format`.The code was well written and contained semi-colons already. I looked at 10 files and saw no issues but the rules were still missing - good to formally enforce

**Comment by bklynate** [comment]
@Abhishek-kumar09 @maverick-27 - will this PR get merged?

**Comment by Abhishek-kumar09** [comment]
Yes, it will be reviewed by the project maintainer then be merged. I am adding it to hacktoberfest label incase you were looking for that in this PR. We are currently busy with designs implementation for the new pages and other such stuffs, though your PR is remarkable.

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
