### PR TITLE
Added validation to campus leader application form

### PR DESCRIPTION
**Pull request by Saif807380**
Also changed year field to a select dropdown. All changes were made to `/src/views/pages/CLView/ApplyNowModal.js`. All other changes were made by `npm run format`.

### CODE REVIEW

**Comment by Saif807380** [comment]
[Link to preview](https://5f6a34ae7f47880008b36083--eloquent-turing-542749.netlify.app/campusLeaders)

**Comment by Abhishek-kumar09** [comment]
@Saif807380 Your changes are excellent and working fine, but there is lot of indentation changes and etc that should not be the part of this PR.
You should revert all the indentation and code formatting changes and leave only those changes which corresponds to this PR.

I thought you would have run `npm run format` (I guess).

**Comment by Saif807380** [comment]
Should I go ahead and revert the changes? If so what would be the best way to do it?

**Comment by Abhishek-kumar09** [comment]
@Saif807380 You can rebase your PR with current changes once https://github.com/codeforcauseorg/codeforcause.org/pull/85 is merged.

> You should revert all the indentation and code formatting changes and leave only those changes which corresponds to this PR.

please ignore this.

**Comment by Abhishek-kumar09** [comment]
> Should I go ahead and revert the changes? If so what would be the best way to do it?
Please wait for a moment, once https://github.com/codeforcauseorg/codeforcause.org/pull/85 is approved by any reviewer then you could rebase the branch.

**Comment by Saif807380** [comment]
Alright.

**Comment by Saif807380** [comment]
There was an issue with the rebasing for this branch with the development branch. It will be better if we close this and I'll delete the branch and work on a new one.

**Pull request closed without merging**
