### PR TITLE
Add stand-for section in home-page

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes Issue #10

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@KeenWarrior @GangaChatrvedi I think there is problem with CI, npm build and npm start is working perfectly in my local system. morever I have not changed files that is related to npm or any packages.

**Comment by GangaChatrvedi** [comment]
The problem is that CI treats warnings as errors. 
ci

Just remove them. This will work.

**Comment by Abhishek-kumar09** [comment]
@GangaChatrvedi Done :+1:

**Comment by GangaChatrvedi** [comment]
This looks good. Although there are some minor corrections.

- Please change background color of the section to #1D006F.
- Change color of cards to #EEF5FF.
- The padding for all the components must be same.You can take reference from ```Hero``` component.

**Comment by Abhishek-kumar09** [comment]
@GangaChatrvedi Done
Earlier: 
image
Newer:
image

**Comment by GangaChatrvedi** [comment]
Looks great :fire:

**Pull request merged**
