### PR TITLE
Created Hire with us component 4

### LINKED ISSUE #223: Create Hire-with-us component 4
The component to make: 
image

Please let me know about the any aditional file you want, and react out for any help with the issue.

### PR DESCRIPTION
**Pull request by niteshsinha17**
It seems font size are bigger in phone view. If you want then we can reduce it.
closes #223

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@niteshsinha17 
For the mobile view, it will be good we have image, then text then button. Sorry I gave the wrong suggestion earlier.
image

**Comment by niteshsinha17** [comment]
No problem I will change it.

**Comment by niteshsinha17** [comment]
@Abhishek-kumar09 I have changed it. Please check

**Comment by Abhishek-kumar09** [comment]
Thanks @niteshsinha17 for your PR, the changes are looking good!

**Pull request merged**
