### PR TITLE
Philosphy Component Added

### LINKED ISSUE #202: Create Hire-With-Us component 3
Here is the component design: 
image
here is the full prototype #199

### PR DESCRIPTION
**Pull request by atharmohammad**
Fix #202 

Added Component Philosphy in Hire With us 
update

### CODE REVIEW

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  Review the Changes and let me know

**Comment by Abhishek-kumar09** [comment]
Looks good, breaks on mobile. But currently I dont have mobile view. so changes are OK for me.

**Comment by Abhishek-kumar09** [comment]
This thing breaks on firefox with 100% zoom level: 
image

**Comment by atharmohammad** [comment]
> This thing breaks on firefox with 100% zoom level:
> image

Yes I see It's breaking on 110% zoom actually , What do you suggest,add some media-query for this?

**Comment by atharmohammad** [comment]
> Looks good, breaks on mobile. But currently I dont have mobile view. so changes are OK for me.

Yes it breaking on mobile ,I will try to add some media queries

**Comment by Abhishek-kumar09** [comment]
> Yes it breaking on mobile ,I will try to add some media queries

You can do it with material-ui breakpoints: https://material-ui.com/customization/breakpoints/

**Comment by atharmohammad** [comment]
> > Yes it breaking on mobile ,I will try to add some media queries
> 
> You can do it with material-ui breakpoints: https://material-ui.com/customization/breakpoints/
> 
> Some files have these already implemented.

Ok, I will see and implement it

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  made the changes ,review it

**Comment by Abhishek-kumar09** [comment]
Please resolve merge conficts.

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  Done 👍

**Comment by Abhishek-kumar09** [comment]
Excellent changes, loving your work. Thanks for the PR.

**Pull request merged**
