### PR TITLE
Responsive Development Component

### LINKED ISSUE #228: Developer Component is not Mobile Friendly
dev

### This Component was Breaking in mobile .
(https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/HireWithUsView/Developer/Developer.js )

### PR DESCRIPTION
**Pull request by atharmohammad**
Fix #228

### CODE REVIEW

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  Review the changes, Thanks 👍

**Comment by Abhishek-kumar09** [comment]
make it center aligned: 
Screen Shot 2021-02-15 at 19 21 47

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  Done 💯

**Comment by Abhishek-kumar09** [comment]
Just awesome, looks much better now.

**Comment by Abhishek-kumar09** [comment]
Thanks for the PR.

**Comment by atharmohammad** [comment]
> Just awesome, looks much better now.

Yess 🥇

**Pull request merged**
