### PR TITLE
add responsive standfor page to show fullly aligned contents on md and sm screens.

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
@KeenWarrior please review.

checked responsive behaviour on all screens

### CODE REVIEW

**Comment by GangaChatrvedi** [comment]
@Abhishek-kumar09 there are changes in the content of this section so I've updated that. You can check it [here](https://sandbox.codeforcause.org/home#about).

For mobile screen, we'll not show the details but only icon and its corresponding heading/title below each icon, both horizontally center aligned.

**Comment by Abhishek-kumar09** [comment]
Now, medium screens like ipod have both the subpage, is it intended. It looks compact there.
Screen Shot 2020-07-25 at 22 55 15

**Comment by Abhishek-kumar09** [comment]
@GangaChatrvedi ping!

**Comment by GangaChatrvedi** [comment]
We can keep only one column for the screen width for medium screen.

**Comment by Abhishek-kumar09** [comment]
Done

**Pull request merged**
